name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.103
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Build publishable XboxWebApi.Cli
      run: |
        dotnet publish -c Release -r win-x86 -o win-x86 XboxWebApi.Cli
        dotnet publish -c Release -r win-x64 -o win-x64 XboxWebApi.Cli
    - name: Upload x86 artifact
      uses: actions/upload-artifact@v2
      with:
        name: XboxWebApiCli-%APPVEYOR_REPO_TAG_NAME%-windows-x86.zip
        path: XboxWebApi.Cli/win-x86/
    - name: Upload x64 artifact
      uses: actions/upload-artifact@v2
      with:
        name: XboxWebApiCli-%APPVEYOR_REPO_TAG_NAME%-windows-x64.zip
        path: XboxWebApi.Cli/win-x64/
    - name: Create tag and publish to nuget
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: XboxWebApi/XboxWebApi.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}